"""
reporter.py — HTML + JSON Report Generator
--------------------------------------------
Generates two output artefacts:
  1. report.html  — colour-coded, human-readable investigation report
  2. findings.json — SIEM-ingestible structured JSON

Jinja2 is used for HTML templating. The JSON format is kept simple enough
to ingest into Splunk, Elastic SIEM, or any log aggregator.
"""

import json
import os
from datetime import datetime, timezone


SEVERITY_COLORS = {
    "CRITICAL": "#c0392b",
    "HIGH":     "#e67e22",
    "MEDIUM":   "#f1c40f",
    "LOW":      "#27ae60",
}

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>NetSentinel Investigation Report</title>
<style>
  body { font-family: 'Segoe UI', sans-serif; background:#0d1117; color:#c9d1d9; margin:0; padding:2rem; }
  h1 { color:#58a6ff; border-bottom:1px solid #30363d; padding-bottom:0.5rem; }
  h2 { color:#8b949e; font-size:0.9rem; font-weight:400; margin-top:0; }
  .meta { background:#161b22; border:1px solid #30363d; border-radius:8px; padding:1rem 1.5rem; margin-bottom:2rem; }
  .meta table { border-collapse:collapse; width:100%; }
  .meta td { padding:4px 12px 4px 0; font-size:0.9rem; }
  .meta td:first-child { color:#8b949e; width:140px; }
  .meta code { background:#0d1117; padding:2px 6px; border-radius:4px; font-size:0.85rem; }
  .badge { display:inline-block; padding:2px 10px; border-radius:12px; font-size:0.78rem;
           font-weight:600; color:#fff; }
  .findings { display:grid; gap:0.75rem; }
  .finding { background:#161b22; border:1px solid #30363d; border-left:4px solid; border-radius:8px;
             padding:0.75rem 1rem; }
  .finding-header { display:flex; align-items:center; gap:0.75rem; margin-bottom:0.25rem; }
  .finding-name { font-weight:600; font-size:0.95rem; }
  .finding-detail { font-size:0.85rem; color:#8b949e; }
  .finding-meta { display:flex; gap:1rem; font-size:0.8rem; color:#6e7681; margin-top:0.4rem; }
  .stat-grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(140px,1fr)); gap:1rem; margin-bottom:2rem; }
  .stat-card { background:#161b22; border:1px solid #30363d; border-radius:8px; padding:1rem; text-align:center; }
  .stat-num { font-size:1.8rem; font-weight:700; color:#58a6ff; }
  .stat-label { font-size:0.8rem; color:#8b949e; margin-top:0.25rem; }
  .hash-box { background:#0d1117; border:1px solid #30363d; border-radius:6px; padding:0.5rem 1rem;
              font-family:monospace; font-size:0.8rem; margin-top:0.5rem; }
  footer { margin-top:3rem; border-top:1px solid #30363d; padding-top:1rem;
           font-size:0.8rem; color:#6e7681; }
</style>
</head>
<body>
<h1>🛡️ NetSentinel — Investigation Report</h1>
<h2>Generated {{ timestamp }}</h2>

<div class="stat-grid">
  <div class="stat-card"><div class="stat-num">{{ stats.total_packets }}</div><div class="stat-label">Packets analysed</div></div>
  <div class="stat-card"><div class="stat-num">{{ findings|length }}</div><div class="stat-label">Anomalies found</div></div>
  <div class="stat-card"><div class="stat-num" style="color:#c0392b">{{ critical_count }}</div><div class="stat-label">Critical</div></div>
  <div class="stat-card"><div class="stat-num" style="color:#e67e22">{{ high_count }}</div><div class="stat-label">High</div></div>
</div>

<div class="meta">
  <table>
    <tr><td>Source file</td><td>{{ source_file }}</td></tr>
    <tr><td>MD5</td><td><code>{{ hashes.md5 }}</code></td></tr>
    <tr><td>SHA256</td><td><code>{{ hashes.sha256 }}</code></td></tr>
    <tr><td>File size</td><td>{{ "{:,}".format(hashes.file_size_bytes) }} bytes</td></tr>
    <tr><td>Analyst</td><td>{{ analyst }}</td></tr>
  </table>
</div>

<h3 style="color:#58a6ff">Findings</h3>
<div class="findings">
{% for f in findings %}
<div class="finding" style="border-left-color:{{ severity_colors[f.severity] }}">
  <div class="finding-header">
    <span class="badge" style="background:{{ severity_colors[f.severity] }}">{{ f.severity }}</span>
    <span class="finding-name">Rule {{ f.rule }} — {{ f.name }}</span>
  </div>
  <div class="finding-detail">{{ f.detail }}</div>
  <div class="finding-meta">
    <span>Src: {{ f.src }}</span>
    <span>Dst: {{ f.dst }}</span>
    <span>Proto: {{ f.protocol }}</span>
    <span>Count: {{ f.count }}</span>
  </div>
</div>
{% else %}
<p style="color:#27ae60">✅ No anomalies detected.</p>
{% endfor %}
</div>

<h3 style="color:#58a6ff">Protocol breakdown</h3>
<div class="meta">
  <table>
  {% for proto, cnt in stats.protocol_breakdown.items() %}
    <tr><td>{{ proto }}</td><td>{{ cnt }}</td></tr>
  {% endfor %}
  </table>
</div>

<footer>Generated by NetSentinel v1.0 | DFIR tool for educational use</footer>
</body>
</html>
"""


def generate_reports(
    findings: list,
    stats: dict,
    hashes: dict,
    source_file: str,
    analyst: str,
    output_dir: str,
) -> tuple:
    """
    Write report.html and findings.json to output_dir.
    Returns (html_path, json_path).
    """
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    critical_count = sum(1 for f in findings if f["severity"] == "CRITICAL")
    high_count     = sum(1 for f in findings if f["severity"] == "HIGH")

    # ── HTML report ──────────────────────────────────────────────────────────
    try:
        from jinja2 import Template
        html = Template(HTML_TEMPLATE).render(
            timestamp=timestamp,
            source_file=source_file,
            hashes=hashes,
            analyst=analyst,
            stats=stats,
            findings=findings,
            severity_colors=SEVERITY_COLORS,
            critical_count=critical_count,
            high_count=high_count,
        )
    except ImportError:
        # Fallback if Jinja2 not installed: produce plain text HTML
        html = f"<pre>NetSentinel Report — {timestamp}\n\n"
        for f in findings:
            html += f"[{f['severity']}] Rule {f['rule']} — {f['name']}\n  {f['detail']}\n\n"
        html += "</pre>"

    html_path = os.path.join(output_dir, "report.html")
    with open(html_path, "w", encoding="utf-8") as fh:
        fh.write(html)

    # ── JSON export ──────────────────────────────────────────────────────────
    report_data = {
        "meta": {
            "tool": "NetSentinel v1.0",
            "generated_at": timestamp,
            "source_file": source_file,
            "analyst": analyst,
            "md5": hashes.get("md5"),
            "sha256": hashes.get("sha256"),
        },
        "summary": {
            "total_packets": stats["total_packets"],
            "anomaly_count": len(findings),
            "critical": critical_count,
            "high": high_count,
        },
        "findings": findings,
        "protocol_breakdown": stats.get("protocol_breakdown", {}),
    }
    json_path = os.path.join(output_dir, "findings.json")
    with open(json_path, "w", encoding="utf-8") as fh:
        json.dump(report_data, fh, indent=2)

    return html_path, json_path
